# file system/dockerfile.legacy v1
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
	python3 build-essential python2.7 libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip xz-utils ca-certificates \
	&& update-ca-certificates \
	&& ln -sf /usr/bin/python2.7 /usr/bin/python \
	&& rm -rf /var/lib/apt/lists/*
COPY system/openssl.cnf /etc/ssl/openssl.cnf
WORKDIR /builder_workspace
